oka_pagination:
    db_driver: orm
    twig: 
        enabled: false
    filters:
        createdAt:
            cast_type: datetime
        name:
            property_name: name    
            cast_type: string
    sort:
        delimiter: ','
        order:
            createdAt: desc
    pagination_managers:
        district:
            db_driver: orm
            class: App\Entity\District
        region:
            db_driver: orm
            class: App\Entity\Region
        department:
            db_driver: orm
            class: App\Entity\Department
        common:
            db_driver: orm
            class: App\Entity\Common
        communalSector:
            db_driver: orm
            class: App\Entity\CommunalSector
        user:
            db_driver: orm
            class: App\Entity\user